In [9]:
import csv
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Embedding, LSTM

from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [10]:

# define 5 documents
docs = ['Well-done!',
		'Good work',
		'Well-done!',
		'Great effort',
		'nice work',
		'Excellent!']
# create the tokenizer
t = Tokenizer(filters='!"#$%&()*+,./:;<=>?@[\\]^_`{|}~\t\n')
# fit the tokenizer on the documents
t.fit_on_texts(docs)
# summarize what was learned
#print(t.word_counts)
#print(t.document_count)
print(t.word_index)
#print(t.word_docs)
# integer encode documents
encoded_docs = t.texts_to_matrix(docs, mode='count')
print(encoded_docs)
encoded_docs.shape

{'well-done': 1, 'work': 2, 'good': 3, 'great': 4, 'effort': 5, 'nice': 6, 'excellent': 7}
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


(6, 8)

In [11]:
encode=t.texts_to_sequences(docs)
print(encode)

[[1], [3, 2], [1], [4, 5], [6, 2], [7]]
